# Generated by Django 4.0.3 on 2022-03-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['pk']},
        ),
    ]
